services:
  db:
    image: mysql:8.0.32
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
    volumes:
      - mysql:/var/lib/mysql

  server-dev:
    profiles:
      - dev
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5080:80
      - 5443:443
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$KESTREL_CERTIFICATE_PASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  server-prod:
    profiles:
      - prod
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5080:80
      - 5443:443
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$KESTREL_CERTIFICATE_PASSWORD
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    #volumes:
    #  - ~/.aspnet/https:/https:ro

volumes:
  mysql: