services:
  db:
    image: mysql:8.0.32
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      retries: 10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mysql:/var/lib/mysql

  server:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - MYSQL_SOURCE=db

  #client:
  #  build: ../CannaLog
  #  restart: unless-stopped
  #  ports:
  #    - 3080:3000


volumes:
  mysql: